apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  selector:
    matchLabels:
      app: app2
  replicas: 3 # tells deployment to run 2 pods matching the template
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: iyadomry/app2
        ports:
        - containerPort: 80
        imagePullPolicy: Always
