apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app2
  name: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app2
    spec:
      containers:
      - image: iyadomry/app2
        name: app2
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: app2
  labels:
    run: app2
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: app2