apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app2
  name: app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app2
        role: rolling-update
    spec:
      containers:
      - image: iyadomry/app2
        name: app2
        ports:
        - containerPort: 80  
    strategy:
    type: RollingUpdate
    rollingUp      maxSurge: 50%
